### ISSUE TITLE
Add SDO service for management hub

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/project-summary#26]
One container image that includes:
- `owner-companion-service` (as-is) and bash/socat-based rest api
  - needs a persistent volume for the json files "DB"
- `owner-protocol-service` (as-is)
  - exposes port 8042 by default
- `to0scheduler` (as-is)
  - exposes port 8049 by default

- [x] Implement ocs sidecar rest api
- [x] Build sdo-owner-services image
- [x] Test with sdo services on separate vm
- [x] Build sample mfg-services image or script
